### ISSUE TITLE
Question: Why not use classes to organise functions

### ISSUE THREAD

**Issue by paulrimiru** [Gilbertly/sls-starter-appsync#78]
I noticed that you organized the  queries and mutations into separate files, while this is a good approach, why did you prefer this approach to using classes to organize them in one place?

**Comment by Gilbertly** [comment]
First, thanks for opening an issue on the repository, I appreciate.
The decision to order the queries and mutations into separate files mainly comes from how "logically-easier" it makes it for someone to scan and understand the code. This follows organizing a specific query/mutation with a descriptive filename, which in this case is also a lambda function, and inspecting the code shows what the function is doing without first inspecting the other files.
While using classes and functions is great, this decision is also not optimal since there's no additional logic that the lambda functions (queries/mutations) are doing, which means that connecting the queries/mutations directly from AppSync to DynamoDB would serve best in this case.

**Comment by paulrimiru** [comment]
Thanks for the reply @Gilbertly , makes sense.
